"""FWU status codes, decoded from Intel's own message table.

Recovered from `FWUpdate/LINUX64/FWUpdLcl` of CSME System Tools v15.0 r15,
sha256 3f9be283b46ac1f9bdd883e05bf71e9d6ace553755fbf3c45b95d1e624f52757.

The binary carries a status-to-index table of 8-byte {u32 status, u32 index}
entries at file offset 0x17a768, and a message block of 1008-byte records
whose short text starts at +0. Resolving one against the other gives the text
below. The decode validates itself: the statuses seen live while probing the
command space resolve to exactly the errors those probes should provoke, for
example a header-only FWU_START returning 0x2C0, "Heci message length is not
as expected".
"""

# status -> short description, verbatim from Intel's message block.
STATUS_TEXT = {
    0x001: 'UPID feature is not supported.',
    0x002: 'Incorrect API version.',
    0x004: 'Command is not supported after EOP.',
    0x005: 'The requested size of partition to read/write/erase exceeds the actual partition size.',
    0x006: 'Flash wear out violation.',
    0x007: 'Flash corruption.',
    0x008: 'Profile is not selectable in BIOS.',
    0x009: 'Profile index is too large.',
    0x00A: 'No such profile in flash.',
    0x00B: 'Command is not supported after EOP.',
    0x00C: 'No such record.',
    0x00D: 'File not found.',
    0x00E: 'Invalid record format.',
    0x00F: 'UOB record is too large.',
    0x010: 'Clock is not configurable',
    0x011: 'Register is locked.',
    0x012: 'No valid PRE UOB.',
    0x013: 'No valid PERM UOB.',
    0x014: 'No data for this clock.',
    0x015: 'Profile index is current.',
    0x016: 'No bclk adjustment found.',
    0x017: 'Warm reset ramp is not supported.',
    0x018: 'UOB record is already invalid.',
    0x019: 'No profile exists.',
    0x01A: 'Authentication failure.',
    0x01B: 'Pending file.',
    0x01C: 'Frequency is too high.',
    0x01D: 'Frequency is too high.',
    0x01E: 'Pending to revert to default.',
    0x01F: 'Pending to set profile.',
    0x020: 'Invalid profile',
    0x021: 'Invalid OEM data.',
    0x022: 'Failed to read dynamic record.',
    0x023: 'PMC rejected MPHY table.',
    0x024: 'Frequency is too low.',
    0x025: 'Frequency is too low.',
    0x026: 'Specified register does not exist.',
    0x02C: 'SSC mode change is not supported.',
    0x02D: 'Range Violation: SSC is too high.',
    0x032: 'Survivability sync disabled.',
    0x033: 'Warm reset required is too low.',
    0x034: 'Specified target ID does not exist.',
    0x035: 'Specified register does not exist.',
    0x036: 'Invalidate successful.',
    0x037: 'Buffer is too small.',
    0x038: 'Valid UOB already present.',
    0x039: 'Waiting for power cycle.',
    0x03A: 'Survivability table access violation.',
    0x03B: 'Survivability table is too large.',
    0x03C: 'EID does not exist.',
    0x03D: 'Success translate only.',
    0x040: 'CMD not supported before DID.',
    0x041: 'FIA MUX error - max config sku mismatch.',
    0x042: 'FIA MUX error - no config found.',
    0x043: 'FIA MUX error - getting laned limit.',
    0x044: 'FIA MUX error - reading configuration from file.',
    0x045: 'EOM config file size is incorrect.',
    0x046: 'Invalid FIA MUX configuration.',
    0x047: 'FIA MUX error - reading configuration to file.',
    0x048: 'FIA MUX error - reading configuration from straps.',
    0x049: 'Wrong PTT disabled Algorithms set.',
    0x04A: 'Failure in reading PCIe Data.',
    0x04B: 'Failure in writing PCIe Data.',
    0x04D: 'Invalid PCIe configuration data.',
    0x059: 'It is not allowed to disable [Intel(R) Network Services Supported] while other manageability configurations are enabled',
    0x07D: 'One or more GPIO pads provided in file have invalid pad address set (group / pad number).',
    0x07E: 'Two or more GPIO pads provided in file have same pad address set.',
    0x080: 'Failed to enable DAM. Hotham generic execution error is expected when booting on disabled mode.',
    0x081: 'Specified partition was not found in the Update Image.',
    0x085: 'Unexpected internal FW error occurred. Invalid parameter.',
    0x089: 'Intel (R) ME Interface : Message type is not supported by FW.',
    0x08B: 'FW Flash read/write/erase operation failed.',
    0x08D: 'FW Update process received Heci command message with unknown command type.',
    0x08F: 'Update Image size exceeds allocated buffer.',
    0x091: 'Invalid Update Image length, size is smaller than required.',
    0x095: 'Firmware Update operation not initiated because a firmware update is already in progress.',
    0x09C: 'AMT is provisioned. Updating AMT vars at this stage is not supported.',
    0x09D: 'Invalid privacy level file.',
    0x09E: 'Unsupported combination of EHBC state and privacy level files.',
    0x09F: 'Invalid EHBC state file.',
    0x0A0: 'Invalid configuration server FQDN value.',
    0x0A1: 'Invalid PKI suffix file.',
    0x0A4: 'Invalid idle timeout file.',
    0x0A5: 'Invalid provisioning state file.',
    0x0A6: 'Invalid all hashes state file.',
    0x0A7: 'Invalid user consent policy file.',
    0x0A8: 'Invalid redirection state file.',
    0x0A9: 'Invalid server address.',
    0x0AB: 'Invalid host FQDN file.',
    0x0AC: 'Invalid host FQDN hostname.',
    0x0AD: 'Invalid host FQDN domain name.',
    0x0AE: 'Invalid cert hash file.',
    0x0B3: 'Invalid value for Signing Policy.',
    0x0B4: 'Invalid value for Reseal Timeout.',
    0x0D1: 'PAVP oem config data: invalid lspcon port value.',
    0x0D2: 'PAVP oem config data: invalid lspcon port count.',
    0x0D3: 'PAVP oem config data: invalid edp port value.',
    0x0D5: 'Conflict in OEM Data: Overlapping values of LSPCON Port Config and eDP Port Config found.',
    0x0D7: 'On board and docked vPro NIC cannot have the same value.',
    0x0D8: 'Retimers cannot have the same I2C address.',
    0x203: 'Sku capabilities bits are different between the Update Image and the Flash Image.',
    0x204: 'Major version number of Update Image is not the same as major version number of Flash Image.',
    0x206: 'Memory allocation error occurred.',
    0x208: 'Firmware update failed due to an internal error The total size of the backup partitions is bigger than NFTP size.',
    0x209: 'Firmware update failed due to an internal error caused by a failure in event publishing.',
    0x20A: 'Firmware Update operation not initiated because a firmware update is already in progress.',
    0x20B: 'Firmware Update operation not initiated because a firmware update is already in progress.',
    0x20C: 'Firmware Update operation not initiated because a firmware update is already in progress.',
    0x20D: 'Firmware Update operation not initiated because a firmware update is already in progress.',
    0x20E: 'Firmware Update operation not initiated because a firmware update is already in progress.',
    0x20F: 'Firmware Update operation not initiated because a firmware update is already in progress.',
    0x210: 'FTPR invalid.',
    0x211: 'NFTP invalid.',
    0x214: 'Host reset is required after the last FW Update operation.',
    0x216: 'Firmware update cannot be initiated because the OEM ID given for FW Update did not match the OEM ID in the FW.',
    0x219: 'Update was blocked by one of the FW modules.',
    0x22A: 'Firmware update failed due to an internal error Write file failed.',
    0x22B: 'Firmware update failed due to an internal error Read file failed.',
    0x22D: 'Sanity check in erase/write of partitions. Error might have happened when size of partition is not 4K aligned.',
    0x22F: 'FW Update is disabled. MEBX has options to disable / enable FW Update.',
    0x233: 'Update to Image with lower ARB SVN is not allowed.',
    0x234: 'Partial update is allowed only to the expected instance ID of an IUP. The Update Image contains IUP with instance ID that is not the currently expe...',
    0x236: 'Partial Update is not allowed, because CSE is in Recovery Mode.',
    0x237: "Partial Update of an IUP was requested, but this IUP doesn't exist in the Flash Image.",
    0x23A: 'Get Restore Point Image is not allowed, because FW Update is in progress. (The regular FW Update will continue).',
    0x23B: 'Update to Image with lower TCB SVN is not allowed.',
    0x23C: 'Update to Image with lower VCN is not allowed.',
    0x23D: 'SVN invalid: SVN is too large.',
    0x23E: 'PSVN partition is full, so cannot update to higher SVN.',
    0x23F: 'Restore Point Image was requested, but it is not allowed because CSE is in Recovery Mode.',
    0x24D: 'Firmware update failed due to an internal error 518.',
    0x24E: 'Restore Point Image was requested, but there was Full/Partial FW Update before without Restart after it.',
    0x24F: 'Update to incompatible PMC: The PMC instance ID is different, which may be due to H/LP SKU incompatibility.',
    0x250: 'Update to incompatible H/LP SKU image.',
    0x251: 'Update Image length is bigger than the expected size of the image according to its size in the flash. For example: Error on updating from Consumer...',
    0x252: 'Manifest size in Update Image is too large.',
    0x253: 'Firmware update failed due to an internal error 364.',
    0x254: 'Firmware update failed due to an internal error 365.',
    0x255: 'Failed to verify signature of OEM or RoT key manifests. For example: Error on update from Production to Pre-Production.',
    0x256: 'Firmware update failed due to an internal error 367.',
    0x25D: 'Firmware update failed due to an internal error 368.',
    0x25E: 'Firmware update failed due to an internal error 369.',
    0x25F: 'Manifest not found in partition (in Update or Flash Image).',
    0x260: 'Firmware update failed due to an internal error 371.',
    0x261: 'Loader failed to verify manifest signature of FTPR. Production vs. Pre-Production.',
    0x262: 'Loader failed to verify manifest signature of NFTP.',
    0x263: 'Loader failed to verify manifest signature of IDLM.',
    0x264: 'Loader failed to verify manifest signature of RBE.',
    0x265: 'Loader failed to verify manifest signature of PMC.',
    0x266: 'Loader failed to verify manifest signature of OEM KM.',
    0x267: 'Loader failed to verify manifest signature of WCOD.',
    0x268: 'Loader failed to verify manifest signature of LOCL.',
    0x269: 'Loader failed to verify manifest signature of PCHC.',
    0x26A: 'Loader failed to verify manifest signature of IOMP.',
    0x26B: 'Loader failed to verify manifest signature of NPHY.',
    0x26C: 'Loader failed to verify manifest signature of TBTP.',
    0x26D: 'Loader failed to verify manifest signature of ISHC.',
    0x26E: 'Loader failed to verify manifest signature of IUNIT.',
    0x270: 'Some manifest extension is missing in FTPR.',
    0x271: 'Some manifest extension is missing in NFTP.',
    0x272: 'Some manifest extension is missing in IDLM.',
    0x273: 'Some manifest extension is missing in RBE.',
    0x274: 'Some manifest extension is missing in PMC. Wrong MEU Tool was used to create the partition.',
    0x275: 'Some manifest extension is missing in OEM KM. Wrong MEU Tool was used to create the partition.',
    0x276: 'Some manifest extension is missing in WCOD.',
    0x277: 'Some manifest extension is missing in LOCL.',
    0x278: 'Some manifest extension is missing in PCHC. Wrong MEU Tool was used to create the partition.',
    0x279: 'Some manifest extension is missing in IOMP. Wrong MEU Tool was used to create the partition.',
    0x27A: 'Some manifest extension is missing in NPHY. Wrong MEU Tool was used to create the partition.',
    0x27B: 'Some manifest extension is missing in TBTP. Wrong MEU Tool was used to create the partition.',
    0x27C: 'Some manifest extension is missing in ISHC. Wrong MEU Tool was used to create the partition.',
    0x27D: 'Some manifest extension is missing in IUNIT. Wrong MEU Tool was used to create the partition.',
    0x27F: 'FTPR partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x280: 'NFTP partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x281: 'DLMP partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x282: 'RBEP partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x283: 'PMCP partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x284: 'OEMP partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x285: 'WCOD partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x286: 'LOCL partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x287: 'PCHC partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x288: 'IOMP partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x289: 'NPHY partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x28A: 'TBTP partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x28B: 'ISHC partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x28C: 'IUNP partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x28D: 'RBEP and NFTP must have the same unique build as FTPR, in the Update Image.',
    0x28E: 'The size of an Update partition is bigger than the size of the Flash partition.',
    0x28F: 'Location of partition to backup is not inside NFTP.',
    0x290: 'The number of IUPs in the Update/Flash Image is bigger than MAX_IUPS.',
    0x291: 'Partition name inside IUPs list (in FTPR manifest extension) is not IUP.',
    0x292: 'Non-optional IUP (like LOCL, WCOD) inside IUPs list (in FTPR manifest extension) is not in the Update Image.',
    0x293: 'PMC partition is not in the Update Image.',
    0x294: 'It is not allowed to do Partial Update on this partition.',
    0x295: 'It is not allowed to do Partial Update on Type-C partitions, according to NVAR.',
    0x296: 'RBEP and NFTP must have the same version as FTPR, in the Update Image.',
    0x297: 'RBEP and NFTP must have the same SVN as FTPR, in the Update Image.',
    0x298: 'RBEP and NFTP must have the same VCN as FTPR, in the Update Image.',
    0x299: 'Non-optional IUPs (like LOCL, WCOD) must have the same major build version as FTPR, in the Update Image for Full Update, in the Flash Image for Par...',
    0x29A: 'Update IUP must not have SVN smaller than SVN of Flash IUP.',
    0x29B: 'Update IUP must not have VCN smaller than VCN of Flash IUP.',
    0x29C: 'Update Image length is not the same as Flash Image length.',
    0x29D: 'Update from PV bit ON to PV bit OFF is not allowed.',
    0x29E: 'Update to PV bit OFF on Revenue platform is not allowed.',
    0x29F: 'Update to higher SVN must be an upgrade - to higher build version.',
    0x2A0: 'Update to higher SVN must be to a higher Hot Fix number (the third number in the build version).',
    0x2A1: 'Place holder. This error code will not be returned by the FW.',
    0x2A2: 'Place holder. This error code will not be returned by the FW.',
    0x2A3: 'Place holder. This error code will not be returned by the FW.',
    0x2A4: 'Place holder. This error code will not be returned by the FW.',
    0x2A5: 'PMCP must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update.',
    0x2A6: 'OEMP must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update.',
    0x2A7: 'WCOD must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2A8: 'LOCL must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2A9: 'PCHC must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2AA: 'IOMP must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2AB: 'NPHY must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2AC: 'TBTP must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2AD: 'ISHC must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2AE: 'IUNP must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2B0: 'Non-optional IUP (like LOCL, WCOD) inside IUPs list (in FTPR manifest extension) is not in the Flash Image.',
    0x2B1: 'A partition that was searched in the Update Image is not in it.',
    0x2B2: 'Update between engineering build vs regular build is not allowed. Both builds have to be the same type: regular or engineering build. Engineering b...',
    0x2B3: 'OEM KM partition is not in the Update Image, but ISHC/IUNP is in the Update Image, which is not allowed.',
    0x2B4: 'ISHC/IUNP do not exist in the same way in the Update Image and in the Flash Image.',
    0x2B5: 'OEM KM partition is not in the Flash Image, but it is in the Update Image, which is not allowed.',
    0x2B6: 'Partial FW Update: the Update Image contains IUP that is different than the one that was requested to be updated in the Partial Update command.',
    0x2B7: 'The Partial Update Image size is different than the size of the IUP in it (as it is in the manifest). This means that the Update Image contains mor...',
    0x2B8: 'Firmware update failed due to an internal error 455.',
    0x2B9: 'Firmware update failed due to an internal error 456.',
    0x2BA: 'Invalid FW Update enabled state.',
    0x2BC: 'Firmware update failed due to an internal error 458.',
    0x2BD: 'Firmware update failed due to an internal error 459.',
    0x2BE: 'Get Restore Point Image is not allowed, because a previous Get Restore Point operation already started. Both operations will be aborted. (Get Resto...',
    0x2BF: 'Firmware update failed due to an internal error 461.',
    0x2C0: 'Heci message length is not as expected.',
    0x2C1: 'FWU_START_MSG Heci message contains invalid value in UpdateEnvironment. Value should be FWU_ENV_MANUFACTURING. (Other possible value: FWU_ENV_IFU i...',
    0x2C2: "FWU_DATA Heci command was sent, but the FW Update wasn't started with FWU_START Heci command before it.",
    0x2C3: 'FWU_DATA Heci command has invalid data length (too big).',
    0x2C4: 'FWU_END Heci command was sent, but there was no FWU_DATA command before it.',
    0x2C5: 'Firmware update failed due to an internal error 478.',
    0x2C6: 'Firmware update failed due to an internal error 477.',
    0x2C7: 'Firmware update failed due to an internal error 476.',
    0x2C8: 'Flash Image content is invalid.',
    0x2C9: 'Wrong structure of Update Image.',
    0x2CA: 'Update to higher TCB SVN must be also to higher ARB SVN.',
    0x2CB: 'Loader failed to verify manifest signature of SPHY.',
    0x2CC: 'Some manifest extension is missing in SPHY. Wrong MEU Tool was used to create the partition.',
    0x2CD: 'SPHY partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x2CE: 'SPHY must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2CF: 'FW Update is not possible on UFS Flash after End Of Post (after the OS is running). It is possible only before the OS is running using Bios Capsule...',
    0x2D0: 'Firmware update failed due to an internal error 465.',
    0x2D1: 'Firmware update failed due to an internal error 501.',
    0x2D2: 'PCHC partition is not in the Update Image.',
    0x2D3: 'CSE is in Recovery Mode but FWSTS registers report Normal Mode.',
    0x2D4: 'The Flash Image that was burned on the platform was corrupted. CSE is in Recovery Mode at first boot.',
    0x2D5: 'Update of partition between engineering build vs regular build is not allowed.',
    0x2D6: 'Update FTPR must have the same NVM compatibility (SPI/UFS) as Flash FTPR.',
    0x2D7: 'Update RBEP must have the same NVM compatibility (SPI/UFS) as Flash RBEP.',
    0x2D8: 'Update NFTP must have the same NVM compatibility (SPI/UFS) as Flash NFTP.',
    0x2D9: 'Update IUP must have the same NVM compatibility (SPI/UFS) as Flash IUP.',
    0x2DA: 'Loader failed to verify manifest signature of ISIF.',
    0x2DB: 'Some manifest extension is missing in ISIF. Wrong MEU Tool was used to create the partition.',
    0x2DC: 'ISIF partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x2DD: 'ISIF must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2DE: 'Loader failed to verify manifest signature of ADSP.',
    0x2DF: 'Some manifest extension is missing in ADSP. Wrong MEU Tool was used to create the partition.',
    0x2E0: 'ADSP partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x2E1: 'ADSP must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2E2: 'Update FTPR must have the same FW Type and Sub-Type as Flash FTPR.',
    0x2E3: 'Loader failed to verify manifest signature of SAMF.',
    0x2E4: 'Some manifest extension is missing in SAMF. Wrong MEU Tool was used to create the partition.',
    0x2E5: 'SAMF partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x2E6: 'SAMF must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2E7: 'Loader failed to verify manifest signature of PPHY.',
    0x2E8: 'Some manifest extension is missing in PPHY. Wrong MEU Tool was used to create the partition.',
    0x2E9: 'PPHY partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x2EA: 'PPHY must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2EB: 'Loader failed to verify manifest signature of GBST.',
    0x2EC: 'Some manifest extension is missing in GBST. Wrong MEU Tool was used to create the partition.',
    0x2ED: 'GBST partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x2EE: 'GBST must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2F1: 'CSE is in Unlocked Mode. FW Update is not possible.',
    0x2F2: 'FWUpdate Data is shorter than the update image length.',
    0x2F3: 'Loader failed to verify manifest signature of PSEP.',
    0x2F4: 'Some manifest extension is missing in PSEP. Wrong MEU Tool was used to create the partition.',
    0x2F5: 'PSEP partition hash and calculated hash are not the same. If partition hash is zero - wrong MEU Tool was used to create the partition.',
    0x2F6: 'PSEP must have the same major API version as the version inside the list in FTPR, in the Update Image for Full Update, in the Flash Image for Parti...',
    0x2F7: 'Resource allocation error.',
    0x500: 'Max bundles record reached.',
    0x501: 'Specified PLL is not supported',
    0x502: 'Data item unsupported.',
    0x503: 'Oem profile card violation.',
    0x9C4: 'AMT Ipv4 Interface is disabled.',
    0x9C5: 'Interface does not exists.',
}

# Codes seen live that are absent from Intel's table would go here. There are
# currently none: every status this client has provoked resolves above. The
# 0xFF / 0x8D refusal envelope, for instance, decodes to "FW Update process
# received Heci command message with unknown command type", which is exactly
# what the command-space probe took it to mean.
OBSERVED = {}

# Note on the UpdateEnvironment probe. Sending FWU_START with image_length 0
# gave 0x206 for env 0 and 0x81 for env 1, 2 and a bogus 0x5A, which is how
# env 0 was first singled out. The table above shows those codes do not
# actually mean "bad environment" (0x2C1 does), so that reasoning was weaker
# than it looked. The value is nonetheless settled: Intel's own caller passes
# it as a literal zero, `xor edx, edx` at 0x17894 in the v15 Linux build.

SUCCESS = 0x000


def describe(status: int) -> str:
    """Render a status code as text, falling back to the raw value."""
    if status == SUCCESS:
        return "success"
    if status in STATUS_TEXT:
        return STATUS_TEXT[status]
    if status in OBSERVED:
        return OBSERVED[status]
    return f"undocumented status 0x{status:X}"
